# ========== H2 DATABASE ==========
spring.datasource.url=jdbc:h2:mem:gmsi_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ========== H2 CONSOLE (interface web) ==========
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ========== JPA / HIBERNATE ==========
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=false

# ========== SERVEUR ==========
server.port=8080